#!/usr/bin/python3
"""find these two primes p and q of given n, n = p x q"""
import sys
from math import ceil, sqrt

with open(sys.argv[1], "r") as fp:
    n = int(fp.readline())
    # check if value is even
    if n % 2 == 0:
        print("{}={}*{}".format(n, int(n / 2), 2))
    # value is odd number
    else:
        e = int(ceil(sqrt(n)))
        while (True):
            f1 = a * a - n
            f = int(sqrt(f1))
            if(f * f == f1):
                break
            else:
                e += 1
        print("{}={}*{}".format(n, e + f, e - f))
